# Generated by Django 4.2 on 2023-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Phone number')),
                ('full_name', models.CharField(blank=True, max_length=50, verbose_name='Full name')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('verification_code', models.IntegerField(verbose_name='Verification code')),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
